version: "3.7"

services:
  centos-base:
    image: vardan/centos:base
    build:
      context: ./centos/base

  centos-basecli:
    image: vardan/centos:basecli
    build:
      context: ./centos/basecli

  ubuntu-base:
    image: vardan/ubuntu:base
    build:
      context: ./ubuntu/base

  ubuntu-basecli:
    image: vardan/ubuntu:basecli
    build:
      context: ./ubuntu/basecli

  ubuntu-php:
    image: vardan/ubuntu:php-7.1
    build:
      context: ./ubuntu/php
      args:
        - PHP_VERSION=7.1

  ubuntu-php-72:
    image: vardan/ubuntu:php-7.2
    build:
      context: ./ubuntu/php
      args:
        - PHP_VERSION=7.2

  ubuntu-php-73:
    image: vardan/ubuntu:php-7.3
    build:
      context: ./ubuntu/php
      args:
        - PHP_VERSION=7.3

  ubuntu-php-74:
    image: vardan/ubuntu:php-7.4
    build:
      context: ./ubuntu/php
      args:
        - PHP_VERSION=7.4

networks:
  default:
